spring:

# Configuration Spring Cloud
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"

# Configuration dataBase
  datasource:
    url: jdbc:postgresql://localhost:5432/school
    username: postgres
    password: root
    hikari:
      maximumPoolSize: 5
      connectionTimeout: 3000

# The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false

# Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: update

## Banner config
  banner:
    location: classpath:config/banner/banner-dev.txt
  main:
    log-startup-info: false
  output:
    ansi:
      enabled: always

# Token
jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiration: 86400

server:
  port: 8060

# Connection to eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
